name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl -sL https://git.io/file-transfer | sh 
      - name: Upload
        run: |
          echo Add other actions to build > 1.txt
          ./transfer image 1.txt
